//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJJM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMember()
        {
            this.tTeacher = new HashSet<tTeacher>();
        }

        public int memberID { get; set; }
        [DisplayName("名")]
        public string m_firstName { get; set; }
        [DisplayName("姓")]
        public string m_lastName { get; set; }
        [DisplayName("生日")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> m_birth { get; set; }
        [DisplayName("性別")]
        public string m_gender { get; set; }
        [DisplayName("電子信箱(帳號)")]
        [Required(ErrorMessage = "請輸入電子信箱")] /*前端驗證*/
        public string m_email { get; set; }
        [DisplayName("密碼")]
        public string m_password { get; set; }
        [DisplayName("手機")]
        public string m_phone { get; set; }
        [DisplayName("地區")]
        public string m_district { get; set; }
        [DisplayName("地址")]
        public string m_address { get; set; }
        [DisplayName("會員權限")]
        public Nullable<int> m_role { get; set; }
        [DisplayName("興趣")]
        public string m_hobby { get; set; }
        [DisplayName("個人照片")]
        public string m_imgPath { get; set; }
        [DisplayName("JJM點數")]
        public Nullable<int> m_Jpoint { get; set; }

        [DisplayName("姓名")]
        public string m_fullName { get { return m_lastName + m_firstName; } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTeacher> tTeacher { get; set; }
    }
}
