//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJJM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class tTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTeacher()
        {
            this.tClass = new HashSet<tClass>();
        }

        public int teacherID { get; set; }
        [DisplayName("教練證照")]
        public string t_certificateImg { get; set; }
        public HttpPostedFileBase image { get; set; }
        [DisplayName("教練頭銜")]
        public string t_title { get; set; }
        [DisplayName("教練自介")]
        public string t_intro { get; set; }
        [DisplayName("教練留言總數")]
        public Nullable<int> t_messageTotal { get; set; }
        [DisplayName("教練已累積點數")]
        public Nullable<int> t_moneyTotal { get; set; }
        [DisplayName("教練可兌換點數")]
        public Nullable<int> t_money { get; set; }
        [DisplayName("教練已累積學生數")]
        public Nullable<int> t_studentTotal { get; set; }
        [DisplayName("教練已累積課程數")]
        public Nullable<int> t_classTotal { get; set; }
        [DisplayName("教練課程平均評價")]
        public Nullable<double> t_rateAvg { get; set; }
        [DisplayName("教練社群1")]
        public string t_socialMedia1 { get; set; }
        [DisplayName("教練社群2")]
        public string t_socialMedia2 { get; set; }
        [DisplayName("教練社群3")]
        public string t_socialMedia3 { get; set; }
        [DisplayName("教練社群4")]
        public string t_socialMedia4 { get; set; }
        [DisplayName("會員代號")]
        public Nullable<int> memberID { get; set; }

        public virtual tMember tMember { get; set; }
        public virtual tTeacher tTeacher1 { get; set; }
        public virtual tTeacher tTeacher2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClass> tClass { get; set; }
    }
}
