//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJJM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder_Detail
    {
        public int od_itemID { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> classID { get; set; }
        public string c_name { get; set; }
        public Nullable<int> c_price { get; set; }
        public Nullable<int> c_discount { get; set; }
        public Nullable<int> od_profit { get; set; }
    
        public virtual tClass tClass { get; set; }
        public virtual tOrder tOrder { get; set; }
    }
}
