//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjJJM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTeacher()
        {
            this.tClass = new HashSet<tClass>();
            this.tPay = new HashSet<tPay>();
        }

        public int teacherID { get; set; }
        [DisplayName("教練證照1")]
        public string t_certificateImg1 { get; set; }
        public HttpPostedFileBase image1 { get; set; }
        [DisplayName("教練證照2")]
        public string t_certificateImg2 { get; set; }
        public HttpPostedFileBase image2 { get; set; }
        [DisplayName("教練證照3")]
        public string t_certificateImg3 { get; set; }
        public HttpPostedFileBase image3 { get; set; }
        [DisplayName("教練證照列表")]
        public string t_certificateTxt { get; set; }
        [DisplayName("教練頭銜")]
        [Required(ErrorMessage = "請輸入教練頭銜")] /*前端驗證*/
        public string t_title { get; set; }
        [DisplayName("教練自介")]
        public string t_intro { get; set; }
        [DisplayName("教學經歷")]
        public string t_experience { get; set; }
        [DisplayName("教學專長")]
        public string t_expertise { get; set; }
        [DisplayName("教練留言總數")]
        public Nullable<int> t_messageTotal { get; set; }
        [DisplayName("教練已累積點數")]
        public Nullable<int> t_moneyTotal { get; set; }
        [DisplayName("教練可兌換點數")]
        public Nullable<int> t_money { get; set; }
        [DisplayName("教練已累積學生數")]
        public Nullable<int> t_studentTotal { get; set; }
        [DisplayName("教練已累積課程數")]
        public Nullable<int> t_classTotal { get; set; }
        [DisplayName("教練課程平均評價")]
        public Nullable<double> t_rateAvg { get; set; }
        [DisplayName("教練社群1")]
        public string t_socialMedia1 { get; set; }
        [DisplayName("教練社群2")]
        public string t_socialMedia2 { get; set; }
        [DisplayName("教練社群3")]
        public string t_socialMedia3 { get; set; }
        [DisplayName("教練社群4")]
        public string t_socialMedia4 { get; set; }
        [DisplayName("會員代號")]
        public Nullable<int> memberID { get; set; }
        [DisplayName("轉職時間")]
        public Nullable<System.DateTime> t_getNow { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tClass> tClass { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPay> tPay { get; set; }
    }
}
